POSTGRES_USER: postgres
DISCORD_CLIENT_SECRET: tx7C-FV8mvtuNAbhkBWMTf7r_x7yre58
PATREON_REDIRECT_URI: https://3ade-68-32-213-147.ngrok-free.app/oauth/patreon_callback
POSTGRES_HOST: localhost
DISCORD_API_KEY: MTMxODU5NzIxMDExOTg2NDM4NQ.GfO8rR.ALx90cEIocShZ2GRbf0d4gDs0YqVb17RXY-PXM
POSTGRES_DATABASE: lucy
POSTGRES_PASSWORD: ''
POSTGRES_PORT: '5432'
DISCORD_CLIENT_ID: '1318597210119864385'
SPARK_PATREON_ENDPOINT: oauth/discord_oauth
DISCORD_TESTING_GUILD_ID: '1347284827350630591'
SPARK_DISCORD_ENDPOINT: oauth/discord_oauth
PATREON_CLIENT_ID: 0iTWDbNfDxFJeLRHsCYf_-dn8CDuNOBU7_8DGZ__fgqdqgwOXz3nQEWhBZvEz0GA
DISCORD_REDIRECT_URI: https://3ade-68-32-213-147.ngrok-free.app/oauth/discord_callback
PATREON_API_KEY: ''
DISCORD_ROLE_PASS: '1347284827610812547'
PATREON_CLIENT_SECRET: aXuH42g8qNm4_whJJnsIm52ywAIP43ZQlAPpHq7cUuLV0Vc75RpKr21Q8sYTaXn0
SPARK_PORT: '8000'
DISCORD_COMMAND_PREFIX: '!'
DISCORD_OWNER_ID: '154749533429956608'
